version: '3'
services:
  web:
    build: .
    command: python main.py
    ports:
      - "8080:8080"
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 3001:8080
